# Generated by Django 3.2.8 on 2021-11-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='attachment',
            field=models.FileField(default='SOME STRING', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='register',
            name='description',
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
