# Generated by Django 3.2.8 on 2021-11-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_auto_20211102_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='description',
            field=models.TextField(max_length=299, null=True),
        ),
    ]
